<a href="https://colab.research.google.com/github/santiagolsanchez/Stylo/blob/master/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def jacobi(a,b,ans,initial):
  x1 = initial[0]
  x2 = initial[1]
  x3 = initial[2]
  i = 0
  x = np.array([x1,x2,x3]).reshape((3,1))
  table = pd.DataFrame(columns=['Iteration','x1','x2','x3','Error'])
  ans = ans.reshape((3,1))
  err = abs(ans[0] - x[0]) + abs(ans[1] - x[1]) + abs(ans[2] - x[2])
  table.loc[i] = [i+1,round(x1,4),round(x2,4),round(x3,4),round(err[0],4)]
  while(True):
    X1 = (b[0] - a[0][1]*x2 - a[0][2]*x3)/a[0][0]
    X2 = (b[1] - a[1][0]*x1 - a[1][2]*x3)/a[1][1]
    X3 = (b[2] - a[2][1]*x2 - a[2][0]*x1)/a[2][2]
    x1 = X1
    x2 = X2
    x3 = X3
    x = np.array([x1,x2,x3]).reshape((3,1))
    b1 = b.reshape((3,1))
    t = np.matmul(a,x) - b1 
    err = abs(ans[0] - x[0]) + abs(ans[1] - x[1]) + abs(ans[2] - x[2])
    i = i+1
    table.loc[i] = [i+1,round(x1,4),round(x2,4),round(x3,4),round(err[0],4)]
    
    if(abs(t[0]) < 0.0001 and abs(t[1]) < 0.0001 and abs(t[2]) < 0.0001):
      break
  return table, round(x1,3) , round(x2,3) , round(x3,3)

def gauss_seidel(a,b,ans,initial):
  x1 = initial[0]
  x2 = initial[1]
  x3 = initial[2]
  i = 0
  x = np.array([x1,x2,x3]).reshape((3,1))
  table = pd.DataFrame(columns=['Iteration','x1','x2','x3','Error'])
  ans = ans.reshape((3,1))
  err = abs(ans[0] - x[0]) + abs(ans[1] - x[1]) + abs(ans[2] - x[2])
  table.loc[i] = [i+1,round(x1,4),round(x2,4),round(x3,4),round(err[0],4)]
  while(True):
    X1 = (b[0] - a[0][1]*x2 - a[0][2]*x3)/a[0][0]
    x1 = X1
    X2 = (b[1] - a[1][0]*x1 - a[1][2]*x3)/a[1][1]
    x2 = X2
    X3 = (b[2] - a[2][1]*x2 - a[2][0]*x1)/a[2][2]
    x3 = X3
    x = np.array([x1,x2,x3]).reshape((3,1))
    b1 = b.reshape((3,1))
    t = np.matmul(a,x) - b1 
    err = abs(ans[0] - x[0]) + abs(ans[1] - x[1]) + abs(ans[2] - x[2])
    i = i+1
    table.loc[i] = [i+1,round(x1,4),round(x2,4),round(x3,4),round(err[0],4)]
    
    if(abs(t[0]) < 0.0001 and abs(t[1]) < 0.0001 and abs(t[2]) < 0.0001):
      break
  return table, round(x1,3) , round(x2,3) , round(x3,3)

a = np.array([[4,1,1],[2,-5,1],[1,2,7]])
b = np.array([6,-2,10])
x = np.linalg.solve(a,b)
initial = [0.99,0.99,0.99]
table, x1, x2, x3 = jacobi(a,b,x,initial)
print(x1 , x2 , x3)
table

# table1 , x1 , x2 ,x3 = jacobi(a,b,x,initial) 
# print(x1,x2,x3)
# table1

# table2 , x1, x2, x3 = gauss_seidel(a,b,x,initial)
# print(x1 , x2 , x3)
# table2

# initial = [100,200,100]
# table1 , x1 , x2 ,x3 = jacobi(a,b,x,initial) 
# print(x1,x2,x3)
# table1

# table2 , x1, x2, x3 = gauss_seidel(a,b,x,initial)
# print(x1 , x2 , x3)
# table2

# initial = [1.005,0.994,1.004]
# table1 , x1 , x2 ,x3 = jacobi(a,b,x,initial) 
# print(x1,x2,x3)
# table1

# table2 , x1, x2, x3 = gauss_seidel(a,b,x,initial)
# print(x1 , x2 , x3)
# print(x1,x2,x3)
# table2

1.0 1.0 1.0

   Iteration      x1      x2      x3   Error
0        1.0  0.9900  0.9900  0.9900  0.0300
1        2.0  1.0050  0.9940  1.0043  0.0153
2        3.0  1.0004  1.0029  1.0010  0.0043
3        4.0  0.9990  1.0004  0.9991  0.0022
4        5.0  1.0001  0.9994  1.0000  0.0007
5        6.0  1.0001  1.0001  1.0001  0.0003
6        7.0  1.0000  1.0001  1.0000  0.0002
7        8.0  1.0000  1.0000  1.0000  0.0001
8        9.0  1.0000  1.0000  1.0000  0.0000